# syntax=docker/dockerfile:1.7

FROM node:24-trixie-slim

ENV PIP_DEFAULT_TIMEOUT=300
ENV PIP_RETRIES=10

RUN sed -i 's/Components: main/Components: main contrib non-free non-free-firmware/g' /etc/apt/sources.list.d/debian.sources || \
    sed -i 's/main/main contrib non-free non-free-firmware/g' /etc/apt/sources.list

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ffmpeg \
        ca-certificates \
        openssl \
        yt-dlp \
        python3 \
        python3-pip \
        python3-opencv \
        intel-media-va-driver-non-free \
        libvpl2 \
		libmfx-gen1.2 \
        vainfo \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --break-system-packages --no-cache-dir --upgrade typing-extensions

RUN python3 -m pip install --break-system-packages --no-cache-dir torch==2.7.1+cu128 torchvision==0.22.1+cu128 --index-url https://download.pytorch.org/whl/cu128

RUN python3 -m pip install --break-system-packages --no-cache-dir yt-dlp matplotlib pillow pyyaml requests scipy psutil polars openvino \
	&& python3 -m pip install --break-system-packages --no-cache-dir --no-deps --upgrade ultralytics-thop ultralytics
