# syntax=docker/dockerfile:1.7

FROM node:24-trixie-slim

ENV PIP_DEFAULT_TIMEOUT=300
ENV PIP_RETRIES=10

RUN --mount=type=tmpfs,target=/tmp --mount=type=tmpfs,target=/var/cache/apt apt-get update \
	&& apt-get install -y --no-install-recommends ffmpeg ca-certificates openssl yt-dlp python3-pip python3-opencv intel-media-va-driver i965-va-driver vainfo \
	&& rm -rf /var/lib/apt/lists/*

RUN --mount=type=tmpfs,target=/tmp --mount=type=cache,target=/root/.cache/pip python3 -m pip install --break-system-packages --upgrade typing-extensions

RUN --mount=type=tmpfs,target=/tmp --mount=type=cache,target=/root/.cache/pip python3 -m pip install --break-system-packages torch==2.7.1+cu128 torchvision==0.22.1+cu128 --index-url https://download.pytorch.org/whl/cu128

RUN --mount=type=tmpfs,target=/tmp --mount=type=cache,target=/root/.cache/pip python3 -m pip install --break-system-packages yt-dlp matplotlib pillow pyyaml requests scipy psutil polars openvino \
	&& python3 -m pip install --break-system-packages --no-deps --upgrade ultralytics-thop ultralytics
