services:
  garage-init:
    build:
      context: .
      dockerfile: services/garage/Dockerfile.init

  whisper:
    build:
      context: ./services/whisper
      dockerfile: Dockerfile

  app:
    build:
      context: .
      dockerfile: apps/web/Dockerfile

  db-migrate:
    build:
      context: .
      dockerfile: services/postgres/Dockerfile.migrate

  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
