services:
  ai:
    runtime: runc
    environment:
      WHISPER_DEVICE: cpu
      WHISPER_COMPUTE_TYPE: int8
      WHISPER_CPU_FALLBACK: "true"
      NVIDIA_VISIBLE_DEVICES: void
      WHISPER_DEBUG: ${WHISPER_DEBUG:-false}

  worker:
    runtime: runc
    environment:
      NVIDIA_VISIBLE_DEVICES: void
