services:
  garage-init:
    build:
      context: .
      dockerfile: services/garage/Dockerfile.init

  ai:
    build:
      context: ./services/whisper
      dockerfile: Dockerfile

  worker-base:
    image: ${CLIPSE_WORKER_BASE_IMAGE:-clipse-worker-base:local}
    build:
      context: .
      dockerfile: apps/worker/Dockerfile.base

  app:
    build:
      context: .
      dockerfile: apps/web/Dockerfile

  db-migrate:
    build:
      context: .
      dockerfile: services/postgres/Dockerfile.migrate

  worker:
    build:
      args:
        CLIPSE_WORKER_BASE_IMAGE: ${CLIPSE_WORKER_BASE_IMAGE:-clipse-worker-base:local}
      context: .
      dockerfile: apps/worker/Dockerfile
    depends_on:
      - worker-base
