packages:
  - apps/*
  - services/*

overrides:
  defu@<=6.1.4: '>=6.1.5'
  drizzle-orm@<0.45.2: '>=0.45.2'
  esbuild@<=0.24.2: '>=0.25.0'
  kysely@<=0.28.13: '>=0.28.14'
  kysely@>=0.26.0 <=0.28.11: '>=0.28.12'
  postcss@<8.5.10: '>=8.5.10'
  protobufjs@<7.5.5: '>=7.5.5'
  tar@<7.5.8: '>=7.5.8'
  tar@<=7.5.10: '>=7.5.11'
  tar@<=7.5.9: '>=7.5.10'
